name: checking-the-parallelism
on: [push]


defaults: 
    run: 
        shell: bash

jobs: 
    first-job-cd: 
        runs-on: ubuntu-latest 
        steps: 
            - name: cd deployment 
              run: echo 'hello cd'
             
    learning-literals: 
        runs-on: ubuntu-latest 
        env: ## setting the literals 
            firstEnv: ${{ 'This-is-first-Env-value'}}
            thirdEnv: ${{ 'It''s open source!'}}
        steps: 
            - name: setting literals 
              run: | 
               echo "grabbing firstEnv value ${{ env.firstEnv}}"
               echo "grabbing the thirdEnv value ${{ env.thirdEnv}}"
               echo le"
               
