name: mastering-ci-cd 
on: 
  push: 
    branches: 
    - 'main' 


jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo the hello world 
        run: echo "hello-world"

  creating-custom-variable: 
    runs-on: ubuntu-latest
    steps: 
      - name: creating custom variable 
        ## This env variables will be available in the "app.py" file. If you give env variable as a input, you can do like this. 
        env: 
          DEFALT_PATH: /home/runner/work/mastering-ci-cd
          ARAVIND: aravind
          PORT: 1234 

        run: | 
          python3 /workspaces/mastering-ci-cd/app.py 




