name: mastering-ci-cd 
on: 
  push: 
    branches: 
    - 'main' 

## setting default values for all the workflows 
# defaults: 
#     run: 
#       shell: bash


jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo the hello world 
        run: | 
            echo "hello-world"
            timedatectl

  creating-custom-variable-and-passing-to-file: 
    runs-on: ubuntu-latest
    needs: [first-job] ## this job will run after the first-job 
    
    steps: 
      - uses: actions/checkout@v3
      - run: python3 ./app.py 
        ## This env variables will be available in the "app.py" file. If you give env variable as a input, you can do like this. 
        env: 
          ARAVIND: aravind
          PORT: 1234 
      - run: bash ./script.sh

  saving-the-artificat-job: 
    runs-on: ubuntu-latest 
    needs: [creating-custom-variable-and-passing-to-file]
    
    steps: 
    - shell: bash 
      run: expr 1 + 1 > output.log 
      
    - name: Upload output file
      uses: actions/upload-artifact@v3
      with:
        name: output-log-file
        path: output.log

  downloading-the-artificat-job: 
    runs-on: ubuntu-latest
    needs: [saving-the-artificat-job]

    steps: 
    - name: download the file 
      uses: actions/download-artifact@v3
      with:
        name: output-log-file
    - shell: bash 
      run: |
        ls
        cat output.log 
      


  

      






