name: mastering-ci-cd 
on: 
  push: 
    branches: 
    - 'main' 

# comment 


jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 

    - name: echo the hello world 
      run: echo "hello-world"


