name: mastering-ci-cd 
on: 
  push: 
    branches: 
    - 'main' 

## setting default values for all the workflows 
# defaults: 
#     run: 
#       shell: bash 


jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo the hello world 
        run: | 
            echo "hello-world"
            timedatectl

  creating-custom-variable-and-passing-to-file: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - run: python3 ./app.py 
        ## This env variables will be available in the "app.py" file. If you give env variable as a input, you can do like this. 
        env: 
          ARAVIND: aravind
          PORT: 1234 
      - run: bash ./script.sh

  

      






