name: getting_inputs_testing 

on: 
    workflow_dispatch: 
        inputs: 
            task_json: 
                description: Paste your task json here 
                required: true 
                type: string 

jobs: 
    pasting-properly:  
        runs-on: ubuntu-latest 

        steps: 
            - name: pasting it properly 
              run: echo The json is ${{ inputs.task_json }}

