name: getting_inputs_testing 

on: 
    workflow_dispatch: 
        inputs: 
            task_json: 
                description: Paste your task json here 
                required: true 
                type: string 

env: 
  USER_JSON: ${{ inputs.task_json }}
  INPUT_FILE: ./definition.json


jobs: 
    pasting-properly:  
        runs-on: ubuntu-latest 

        steps: 
            - name: echo the input  
              run: echo The json is ${{ inputs.task_json }}



            - uses: actions/checkout@v3


            # - name: updating the json bro 
            #   uses: restackio/update-json-file-action@v2.0
            #   with:
            #     file: ./definition.json
            #     fields: '{"TASKS": ${{ inputs.task_json}} }'
            # - name: showing the ouput 
            #   run: cat ./definition.json
            - name: now we are changing 
              run: | 
                sed -i "s|##BRANCH##|$USER_JSON|g" $INPUT_FILE
                cat ./definition.json





