name: getting_inputs_testing 

on: 
    workflow_dispatch: 
        inputs: 
            task_json: 
                description: Paste your task json here 
                required: true 
                type: string 

env: 
  USER_JSON: ${{ inputs.task_json }}
  INPUT_FILE: ./definition.json


jobs: 
    pasting-properly:  
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v3
            - name: now we are changing 
              run: | 
                sed -i "s|##OUTPUT##|$USER_JSON|g" $INPUT_FILE
                cat ./definition.json

            - name: commit 
              run: | 
                git config --global user.email "you@example.com"
                git config --global user.name "Your Name"
                git add . 
                git commit -m "added"
                git push 





