name: Greeting on variable day

on:
  pull_request

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona

        
  conditon_job: 
    strategy: 
        matrix: 
            os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os}}
    steps: 
        - name: condition1 
          if: runner.os == 'ubuntu'
          run: echo "The operating system on the runner IS WINDOWS"

        - name: condition 2
          if: runner.os == 'macos'
          run: echo "this is macos operating system"
