name: learning-context
on: 
    push 

jobs: 
    learning-context: 
        strategy: 
            matrix: 
                os: [windows-latest, ubuntu-latest]
                version: [10, 12, 14]
                 
        if: ${{ matrix.os == 'windows-latest'}}
        runs-on: ${{ matrix.os }}
        steps: 
            - name: printing 
            echo: "we are in windows machine"
        
        if: ${{ matrix.os == 'ubuntu-latest'}}
        runs-on: ${{ matrix.os}}
        step: 
        - name: printing 
          echo: "we are in ubuntu-machine"