name: learning-context
on: 
    pull_request 

jobs:
    learning_context: 
        runs-on: ubuntu-latest 
        steps:
            - name: Dump runner context 
              env: 
                GITHUB_CONTEXT: ${{ toJson(runner)}}
              run: echo "$GITHUB_CONTEXT"


