name: learning-workflow-syntax
run-name: this-is-run-name 

on:
    # push: 
    #     branches: 
    #         - main 
    #         - feature
    #     tags: 
    #         - v1
    #         - '!v2'

        # paths: 
        #     - '**.py'


        # tags-ignore: 
        #     - v3
    # label: 
    #     types: 
    #         - created 
    # pull_request: 
    #     branches: 
    #         - main 
    #         - '!releases/**'
        # branches-ignore: 
        #     - 'mona/octocat'


## workflow_dispatch is mannual 
## workflow_call is called by another workflow 
## workflow_run runs the code if another (needs) workflow completed by some other worflow file 
    workflow_dispatch: 
        inputs: 
            username: 
                description: "A suernaem passed"
                default: 'jon-doe'
                type: string 
                required: false 

        


    

jobs: 
    first-job: 
        runs-on: ubuntu-latest
        steps: 
        - run: echo ls